### PR TITLE
Fixes #626

### LINKED ISSUE #626: Duplicate generic methods
The metadata loader creates duplicate generic methods in the type’s method list.

Bug needs to be fixed here:

https://github.com/mosa/MOSA-Project/blob/cf27f7ee4eafd3fdf1a13a1983f5f0947f9903d3/Source/Mosa.Compiler.MosaTypeSystem/Metadata/MetadataLoader.cs#L459

Once resolved, the hack here needs to be removed:

https://github.com/mosa/MOSA-Project/blob/6d96906dce5d015e869c342b8d000ee1f445cd27/Source/Mosa.Compiler.Framework/MosaTypeLayout.cs#L713-L715

### PR DESCRIPTION
**Pull request by charsleysa**

### CODE REVIEW

**Comment by tgiphil** [comment]
Approved.

**Comment by tgiphil** [comment]
See https://github.com/mosa/MOSA-Project/issues/580#issuecomment-544823201

**Comment by arakis** [comment]
Another option would be to reactive PR #690. In that PR I used a Delegate/Hook to generate the FullName. It was only declined, because I used a static Property instead of an instance member. Because I had no idea how to route a CompilerOption to MosaTypeSystem (dependency problem), and tgiphil suggest it would be fine just to make my forced behavior global/default for Mosa-Project, I simply reverted the change and made it like tgiphil suggested.

So, the alternative would be using a Hook/Delegate/OverridableMethod, as I often suggested (adding more hooks to Mosa). Benefit: Implementation work and maintenance for Mosa is minimal, but opens big horizons for developers.

By the way, i still think seperating FullName and SymbolName is useful. But when even hooking the SymbolName, it's the most flexible way. Just a sample: I have three different entrypoints in my KernelService-BInaries: Main, Service and Interrupt. Currently, I need to hardcode the Full Path with Namespace (that makes zero sense, for Example `Lonos.Service.FileSystem.FileService::Main` is located on right place, but should expose the Symbol simply `main`. It's not a discussion about style what I'm doing, it's a discussion that the developer, if he wishes this, is able to use short, useful and customized symbol names. You should let the developer the freedoms as he wants it, not what you want to force him what he should use/not use. Mosa is a compiler, not a style-guide ;-)

**Comment by charsleysa** [comment]
@tgiphil I updated FullName as discussed in #580 though it does look a little strange to see the return type at the end of the full names.

**Comment by arakis** [comment]
Still, incomplete. No SymbolName property and/or alternatively a Delegate/overridable Method to overwrite for customizing the name (in real world, both (symbol name and customization) are required). Please checkout https://github.com/mosa/MOSA-Project/issues/580#issuecomment-545333183, last message, for detailed explanation. I want to underline that this is a hard requirement.

I you want I can help you with that implementation.

**Comment by tgiphil** [comment]
Go ahead and commit. I will push another change that strips out the return type when it emits the symbol name into the ELF file.

**Comment by arakis** [comment]
@tgiphil that's ok. Please don't forget to strip all whitespaces, too, and do not forget DWARF symbols.

**Comment by tgiphil** [comment]
Please add a single colon before the return time and with any spaces around the colon.

**Comment by tgiphil** [comment]
Also this commit break the following unit test:

FAILED: InterfaceTests::InterfaceTest4()

**Pull request merged**
