### PR TITLE
Select VBE Mode Option

### PR DESCRIPTION
**Pull request by CSharpLover**
VBE Mode select option is added, now user can select their modes.

### CODE REVIEW

**Comment by charsleysa** [comment]
@CSharpLover I have performed a quick code review and have rejected this on the grounds that your code formatting does not follow the project requirements.

I would recommend installing EditorConfig plugin for your IDE as described in the Readme so that your IDE is automatically configured when you work on this project.

**Comment by CSharpLover** [comment]
What kind of problems there in my code?

I can fix and recreate a pr...

**Comment by charsleysa** [comment]
Code formatting, mainly indentation doesn't match project requirements.

**Comment by CSharpLover** [comment]
For example?
How should my code look like?

**Pull request closed without merging**
