### PR TITLE
Use KeyedCollection for GenericArguments on MosaType and MosaMethod

### PR DESCRIPTION
**Pull request by GeroL**

### CODE REVIEW

**Review by charsleysa — APPROVED** [review]
LGTM

**Comment by tgiphil** [comment]
Let's fix the build error:

Run microsoft/setup-msbuild@v1.0.1
C:\ProgramData\Chocolatey\bin\vswhere.exe -products * -requires Microsoft.Component.MSBuild -property installationPath -latest
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise
Error: Unable to process command '::add-path::C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin' successfully.
Error: The `add-path` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

**Comment by charsleysa** [comment]
@tgiphil I think this should be done as a separate PR as the code change in this PR did not cause the builds to fail.

**Comment by tgiphil** [comment]
> @tgiphil I think this should be done as a separate PR as the code change in this PR did not cause the builds to fail.

Agreed. I think you did that. I'm not sure why this still isn't working. Is it locked into a specific folk on master now?

**Comment by charsleysa** [comment]
@tgiphil I think @GeroL needs to merge mosa/master into his branch

**Comment by GeroL** [comment]
Will do that tomorrow

**Comment by tgiphil** [comment]
Approved. This has been tested in my personal repo without any issue.

**Comment by charsleysa** [comment]
As @tgiphil has tested and approved this PR I will squash merge.

**Pull request merged**
