### PR TITLE
Release V2

### PR DESCRIPTION
**Pull request by tgiphil**

### CODE REVIEW

**Comment by charsleysa** [comment]
Plz, no more 500+ file PRs

**Comment by charsleysa** [comment]
Also, I review and approve an override of the failed AppVeyor check as it will no longer be used.

Though whats the "Windows Test" check? I can't see it in the GitHub YAML files

**Comment by tgiphil** [comment]
> Though whats the "Windows Test" check? I can't see it in the GitHub YAML files

Yeah... No idea at the moment.

**Comment by charsleysa** [comment]
> > Though whats the "Windows Test" check? I can't see it in the GitHub YAML files
> 
> Yeah... No idea at the moment.

Ah, I figured it out, it was the name of the old Github check on Windows, and since it has been marked as `Required` in the branch protection settings it want's it to be there. I think what will need to happen is you'll need to modify the branch protection settings (something only an admin can do) and remove the requirement for the "Windows Test". After that you can use admin rights to merge this PR so that you can ignore that awaiting/failed checks that will no longer exist.

**Pull request merged**
