### PR TITLE
WIP - x64 Support

### PR DESCRIPTION
**Pull request by tgiphil**
Added x64 Instincts and untested code to enter long mode.

### CODE REVIEW

**Comment by charsleysa** [comment]
Is this ready to be reviewed and merged?

**Comment by tgiphil** [comment]
> Is this ready to be reviewed and merged?

Yes, merge but only review changes unrelated to x64. 

The x64 is incomplete, but enough to incorporate the progress and share with the group.

**Comment by tgiphil** [comment]
Related to https://github.com/mosa/MOSA-Project/issues/570.

**Review by charsleysa — APPROVED** [review]
LG

**Pull request merged**
