### PR TITLE
Update to .NET 8.0, Avalonia 11.0.9 and fix launcher issue

### PR DESCRIPTION
**Pull request by AnErrupTion**
- Update to .NET 8.0
- Update to Avalonia 11.0.9
- Don't load MosaSettings again in BaseLauncher.cs and MosaCompiler.cs as they're already initialized by the caller; and make sure they're actually initialized everywhere (e.g. in UnitTestSystem.cs)
- Delete unused backup C# project files

### CODE REVIEW

**Review by charsleysa — CHANGES_REQUESTED** [review]
Missing some changes, the Directory.Build.props file needs to be updated as well as korlib

**Comment by charsleysa** [comment]
Sorry, don't know how I missed that the Directory.Build.props file was already updated.

In regards to korlib, I believe this line has to be updated to match the dotnet version
https://github.com/mosa/MOSA-Project/blob/2eeffe43249819413c472f225a61963fb7c0e32e/Source/Mosa.Korlib/Mosa.Korlib.csproj#L10

**Review by charsleysa — APPROVED** [review]
LGTM

**Comment by AnErrupTion** [comment]
> In regards to korlib, I believe this line has to be updated to match the dotnet version

Oh yeah I forgot about the assembly version! It's not technically required to update it, but it makes things more consistent. Thanks! It's updated now :D

**Pull request merged**
